"""Type stubs for the rsimulator Rust extension."""

from typing import Any

class FlatGpTree:
    """Opaque wrapper around a Rust GP tree used for GP-based strategies."""

    ...

class NativeDispatchStrategy:
    """Opaque wrapper around a native Rust dispatch strategy."""

class NativeEventCallback:
    """Opaque wrapper around a native Rust action callback."""

class Simulator:
    """Rust-backed DVRPTW simulator."""

    def __init__(
        self,
        instance: Any,
        strategy: NativeDispatchStrategy,
        action_callback: NativeEventCallback | None = None,
    ) -> None: ...
    def run(self) -> dict[str, Any]: ...

def greedy_strategy() -> NativeDispatchStrategy: ...
def composable_strategy(router: Any, scheduler: Any) -> NativeDispatchStrategy: ...
def batch_composable_strategy(
    router: Any, scheduler: Any, slot_size: float
) -> NativeDispatchStrategy: ...

# GP strategy helpers (exported from the Rust extension). Tests and the
# Python code expect these names to exist; keep them typed as `Any` to
# avoid coupling the stubs to the concrete Rust implementation.
def gp_strategy(
    routing: FlatGpTree, sequencing: FlatGpTree, reject: FlatGpTree
) -> NativeDispatchStrategy: ...
def flat_gp_const(value: float) -> FlatGpTree: ...
def flat_gp_add(a: FlatGpTree, b: FlatGpTree) -> FlatGpTree: ...
def flat_gp_sub(a: FlatGpTree, b: FlatGpTree) -> FlatGpTree: ...
def flat_gp_mul(a: FlatGpTree, b: FlatGpTree) -> FlatGpTree: ...
def flat_gp_div(a: FlatGpTree, b: FlatGpTree) -> FlatGpTree: ...
def flat_gp_travel_time() -> FlatGpTree: ...
def flat_gp_window_earliest() -> FlatGpTree: ...
def flat_gp_window_latest() -> FlatGpTree: ...
def flat_gp_time_until_due() -> FlatGpTree: ...
def flat_gp_demand() -> FlatGpTree: ...
def flat_gp_current_load() -> FlatGpTree: ...
def flat_gp_remaining_capacity() -> FlatGpTree: ...
def flat_gp_release_time() -> FlatGpTree: ...
